name = "AdsorbedSolutionTheory"
uuid = "c62cc850-d7ca-4cc1-a95b-48008b40dc90"
authors = ["Andrés Riedemann <longemen3000@gmail.com> and contributors"]
version = "1.0.0"

[deps]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LogExpFunctions = "2ab3a3ac-af41-5b50-aa03-7779005ae688"
NLSolvers = "337daf1e-9722-11e9-073e-8b9effe078ba"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[weakdeps]
Clapeyron = "7c7805af-46cc-48c9-995b-ed0ed2dc909a"

[extensions]
IASTClapeyronExt = "Clapeyron"

[compat]
Clapeyron = "0.5"
ForwardDiff = "^0.10"
LinearAlgebra = "1"
LogExpFunctions = "^0.3.24"
NLSolvers = "0.5"
julia = "1.9"

[extras]
Clapeyron = "7c7805af-46cc-48c9-995b-ed0ed2dc909a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Clapeyron"]
